# Generated by Django 4.0.3 on 2022-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base64',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64imagedb', models.ImageField(upload_to='base64images')),
            ],
            options={
                'db_table': 'base64',
            },
        ),
    ]
