# Generated by Django 4.0.3 on 2022-04-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base64',
        ),
    ]
