# Generated by Django 4.0.3 on 2022-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base64Image', '0002_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base64images/'),
        ),
    ]
